# Generated by Django 4.0.5 on 2022-06-27 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_user_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='chat.groups'),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_receiver', to='chat.groups'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='groups',
            index=models.Index(fields=['uuid'], name='groups_uuid_2ecadf_idx'),
        ),
        migrations.AddIndex(
            model_name='groups',
            index=models.Index(fields=['created_by'], name='groups_created_0db857_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembers',
            index=models.Index(fields=['uuid'], name='group_membe_uuid_b6d963_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembers',
            index=models.Index(fields=['group'], name='group_membe_group_i_d2cebc_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembers',
            index=models.Index(fields=['member'], name='group_membe_member__54168f_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchat',
            index=models.Index(fields=['uuid'], name='group chat_uuid_c7b2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchat',
            index=models.Index(fields=['sender'], name='group chat_sender__7201b4_idx'),
        ),
        migrations.AddIndex(
            model_name='groupchat',
            index=models.Index(fields=['receiver'], name='group chat_receive_f3fb14_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['uuid'], name='chat_uuid_00904a_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['sender'], name='chat_sender__41f69d_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['receiver'], name='chat_receive_c6d04a_idx'),
        ),
    ]
