# Generated by Django 4.0.5 on 2022-06-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembers',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
